import{currentUnit,moduleStatistics,weekOverview,weekStrip}from'../../core/model.js';
import{formatNumber,formatDistance,escapeHtml,moduleName,moduleColor}from'../../ui/format.js';
import{icons}from'../../ui/icons.js';
const moduleConfig={kraft:{label:'Kraft',icon:icons.strength},rad:{label:'Rad',icon:icons.cycling},wandern:{label:'Wandern',icon:icons.hiking},challenge:{label:'Challenge',icon:icons.challenge}};
function statusFor(state,module){if(module==='kraft')return currentUnit(state)?.name??'Kein Plan';if(module==='rad'||module==='wandern'){const stats=moduleStatistics(state,module);return stats.count?`${stats.count} ${stats.count===1?'Tour':'Touren'} · ${formatDistance(stats.distance)}`:'Noch keine Tour'}const challenges=state.challenges??[];return challenges.length?`${challenges.length} ${challenges.length===1?'Ziel':'Ziele'}`:'Keine Ziele'}
function moduleCards(state){return Object.entries(moduleConfig).map(([id,config])=>`<button class="module-tile ${id}" data-action="module.open" data-module="${id}"><span class="module-icon">${config.icon}</span><span class="module-label">${config.label}</span><span class="module-status">${escapeHtml(statusFor(state,id))}</span></button>`).join('')}
function weekCard(state){const overview=weekOverview(state),rows=overview.rows.filter(row=>row.count>0).map(row=>`<div class="week-module" style="--module-color:${moduleColor(row.module)}"><span class="week-module-name">${moduleName(row.module)}</span><span class="week-module-values"><b>${row.count}</b> ${row.module==='kraft'?(row.count===1?'Einheit':'Einheiten'):(row.count===1?'Tour':'Touren')} <i>·</i> <b>${row.module==='kraft'?`${formatNumber(row.volume,0)} kg`:formatDistance(row.distance)}</b></span></div>`).join('');return`<p class="section-label">Diese Woche</p><section class="panel week-panel"><div class="week-head"><div><strong>${overview.activities}</strong><span>Aktivitäten</span></div><div><strong>${overview.activeDays}</strong><span>aktive Tage</span></div></div><div class="week-modules">${rows||'<p class="empty-copy">Diese Woche noch nichts eingetragen.</p>'}</div></section>`}
function dots(modules,planned){return modules.map(module=>`<span class="activity-dot ${module}"></span>`).join('')+planned.map(module=>`<span class="activity-dot outline ${module}"></span>`).join('')}
function calendarStrip(state){const days=weekStrip(state);return`<p class="section-label">Kalender</p><section class="panel calendar-strip"><div class="calendar-week">${days.map(day=>`<button class="calendar-day ${day.isToday?'today':''} ${day.isFuture?'future':''}" data-action="day.open" data-date="${day.iso}"><span>${day.label}</span><b>${day.day}</b><i>${dots(day.modules,day.planned)}</i></button>`).join('')}</div><button class="calendar-next" data-action="calendar.open" aria-label="Monatskalender öffnen">${icons.chevron}</button></section>`}
export function dashboardView(state){return`<section class="dashboard"><div class="dashboard-heading"><div><span class="eyebrow"><i></i>All-in-One</span><h1>Start</h1></div><button class="icon-button" data-action="settings.open" aria-label="Daten und Einstellungen">${icons.settings}</button></div><div class="module-grid">${moduleCards(state)}</div>${weekCard(state)}${calendarStrip(state)}</section>`}
