import{load,save,reset,importBackup,exportBackup}from'./core/storage.js';
import{route,go,subscribe}from'./core/router.js';
import{todayIso,shiftMonth}from'./core/date.js';
import{dashboardView}from'./features/dashboard/dashboard.js';
import{calendarView,daySheetView}from'./features/calendar/calendar.js';
import{icons}from'./ui/icons.js';
import{escapeHtml,moduleName}from'./ui/format.js';
const main=document.querySelector('#main'),topbar=document.querySelector('#topbar'),overlay=document.querySelector('#overlay-root'),fileInput=document.querySelector('#backup-file');
let state=load(),calendarAnchor=todayIso(),selectedDay=null;const openDaySessions=new Set();
function setAppHeight(){const height=window.visualViewport?.height??window.innerHeight;document.documentElement.style.setProperty('--app-height',`${height}px`)}
setAppHeight();window.addEventListener('resize',setAppHeight);window.visualViewport?.addEventListener('resize',setAppHeight);
function topbarView(current){if(current.name==='dashboard'){topbar.classList.add('hidden');return''}topbar.classList.remove('hidden');const title=current.name==='calendar'?'Kalender':current.name==='settings'?'Daten & Einstellungen':moduleName(current.module);return`<button class="icon-button" data-action="nav.back" aria-label="Zurück">${icons.back}</button><strong>${escapeHtml(title)}</strong><span></span>`}
function settingsView(){return`<section class="settings-page"><span class="eyebrow"><i></i>All-in-One</span><h1>Daten & Einstellungen</h1><section class="panel settings-card"><div><strong>${state.sessions.length}</strong><span>Sessions</span></div><div><strong>${state.bibliothek.length}</strong><span>Aktivitäten</span></div></section><div class="settings-actions"><button class="action-button" data-action="backup.export">${icons.export}<span><strong>Backup exportieren</strong><small>Aktuellen Stand als JSON sichern</small></span></button><button class="action-button" data-action="backup.import">${icons.import}<span><strong>Backup importieren</strong><small>Altes App-Backup wird direkt unterstützt</small></span></button><button class="action-button danger" data-action="backup.reset">${icons.trash}<span><strong>Lokale Daten löschen</strong><small>Nur Daten dieses neuen Projekts</small></span></button></div></section>`}
function modulePreview(module){const labels={kraft:'Als Nächstes portieren wir das vollständige Kraftmodul aus der alten App.',rad:'Das Radmodul folgt nach der Abnahme des Kraftmoduls.',wandern:'Das Wandermodul folgt nach dem Radmodul.',challenge:'Das Challenge-Modul wird zuletzt portiert.'};return`<section class="module-preview ${module}"><span class="eyebrow"><i></i>${escapeHtml(moduleName(module))}</span><h1>${escapeHtml(moduleName(module))}</h1><section class="panel preview-card"><h2>Dashboard-Phase</h2><p>${escapeHtml(labels[module]??'Dieses Modul folgt später.')}</p></section></section>`}
function render(){const current=route();topbar.innerHTML=topbarView(current);document.body.classList.toggle('dashboard-route',current.name==='dashboard');if(current.name==='dashboard')main.innerHTML=dashboardView(state);else if(current.name==='calendar')main.innerHTML=calendarView(state,calendarAnchor);else if(current.name==='settings')main.innerHTML=settingsView();else if(current.name==='module')main.innerHTML=modulePreview(current.module);else main.innerHTML=dashboardView(state);overlay.innerHTML=selectedDay?daySheetView(state,selectedDay,openDaySessions):''}
function downloadBackup(){const blob=new Blob([exportBackup(state)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`all-in-one-backup-${todayIso()}.json`;anchor.click();URL.revokeObjectURL(url)}
document.addEventListener('click',event=>{const element=event.target.closest('[data-action]');if(!element)return;const action=element.dataset.action;if(action==='settings.open')go('/settings');else if(action==='calendar.open'){calendarAnchor=todayIso();go('/calendar')}else if(action==='calendar.shift'){calendarAnchor=shiftMonth(calendarAnchor,Number(element.dataset.step));render()}else if(action==='module.open')go(`/module/${element.dataset.module}`);else if(action==='nav.back')history.back();else if(action==='day.open'){selectedDay=element.dataset.date;openDaySessions.clear();render()}else if(action==='sheet.close'){selectedDay=null;openDaySessions.clear();render()}else if(action==='day.session.toggle'){openDaySessions.has(element.dataset.id)?openDaySessions.delete(element.dataset.id):openDaySessions.add(element.dataset.id);render()}else if(action==='plan.add'){state.termine??=[];state.termine.push({id:`appointment_${Date.now()}_${Math.random().toString(36).slice(2)}`,datum:selectedDay,modul:element.dataset.module,notiz:''});save(state);render()}else if(action==='plan.remove'){state.termine=(state.termine??[]).filter(item=>item.id!==element.dataset.id);save(state);render()}else if(action==='backup.export')downloadBackup();else if(action==='backup.import')fileInput.click();else if(action==='backup.reset'&&confirm('Lokale Daten dieses neuen Projekts wirklich löschen?')){state=reset();selectedDay=null;render()}});
fileInput.addEventListener('change',async()=>{const file=fileInput.files?.[0];if(!file)return;try{state=importBackup(await file.text());save(state);alert('Backup wurde importiert.');go('/');render()}catch(error){alert(`Import fehlgeschlagen: ${error.message}`)}finally{fileInput.value=''}});
subscribe(render);if(!location.hash)history.replaceState(null,'','#/');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);render();
