import{formatMetric,formatNumber,METRICS}from'./core.js';
const C={bg:'#080A0D',card:'#15191F',line:'rgba(255,255,255,.10)',text:'#F6F8FA',muted:'#929BA8'};
const rr=(x,a,b,w,h,r)=>{x.beginPath();x.moveTo(a+r,b);x.arcTo(a+w,b,a+w,b+h,r);x.arcTo(a+w,b+h,a,b+h,r);x.arcTo(a,b+h,a,b,r);x.arcTo(a,b,a+w,b,r);x.closePath()};
export function drawShareCard(d){
 const B=3,W=520,P=32,rows=d.rows||[],H=250+rows.length*52+(d.note?70:0)+70,c=document.createElement('canvas');c.width=W*B;c.height=H*B;const x=c.getContext('2d');x.scale(B,B);
 x.fillStyle=C.bg;x.fillRect(0,0,W,H);rr(x,12,12,W-24,H-24,24);x.fillStyle=C.card;x.fill();
 const g=x.createRadialGradient(W-70,20,5,W-70,20,260);g.addColorStop(0,d.accent+'35');g.addColorStop(1,d.accent+'00');x.save();rr(x,12,12,W-24,H-24,24);x.clip();x.fillStyle=g;x.fillRect(12,12,W-24,280);x.restore();
 let y=58;x.fillStyle=d.accent;x.font='700 12px system-ui';x.fillText(d.eyebrow||'ALL-IN-ONE',P,y);x.textAlign='right';x.fillStyle=C.muted;x.font='400 13px system-ui';x.fillText(d.date,W-P,y);x.textAlign='left';y+=38;
 x.fillStyle=C.text;x.font='800 30px system-ui';let title=String(d.title||'Aktivität');while(x.measureText(title).width>W-P*2&&title.length>4)title=title.slice(0,-2)+'…';x.fillText(title,P,y);y+=38;
 x.fillStyle=C.muted;x.font='700 12px system-ui';x.fillText(d.heroLabel||'ERGEBNIS',P,y);x.textAlign='right';x.fillStyle=d.accent;x.font='800 25px system-ui';x.fillText(d.heroText||'–',W-P,y);x.textAlign='left';y+=27;
 x.strokeStyle=C.line;x.beginPath();x.moveTo(P,y);x.lineTo(W-P,y);x.stroke();y+=27;
 for(const r of rows){x.fillStyle=C.text;x.font='650 15px system-ui';x.fillText(String(r.name).slice(0,42),P,y);y+=20;x.fillStyle=C.muted;x.font='400 13px system-ui';x.fillText(String(r.detail).slice(0,58),P,y);y+=31}
 if(d.note){x.strokeStyle=C.line;x.beginPath();x.moveTo(P,y);x.lineTo(W-P,y);x.stroke();y+=24;x.fillStyle=C.muted;x.font='italic 13px system-ui';x.fillText(String(d.note).slice(0,70),P,y)}
 x.globalAlpha=.55;x.fillStyle=C.muted;x.font='700 11px system-ui';x.fillText('ALL-IN-ONE NEXT',P,H-34);x.globalAlpha=1;return c
}
export async function shareCard(data,name='all-in-one.png'){const c=drawShareCard(data),blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error('Bild konnte nicht erzeugt werden.');const file=new File([blob],name,{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:data.title});return'geteilt'}catch(e){if(e.name==='AbortError')return'abgebrochen'}}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);return'heruntergeladen'}
export const tourShareData=(s,m,accent,formatDate,metrics)=>({accent,eyebrow:m.share?.eyebrow||m.label.toUpperCase(),title:s.title||m.singular,date:formatDate(s.date),heroLabel:m.share?.heroLabel||'ERGEBNIS',heroText:metrics[m.share?.hero||'distance']!=null?formatMetric(m.share?.hero||'distance',metrics[m.share?.hero||'distance']):'–',rows:m.metrics.filter(t=>t!==(m.share?.hero||'distance')&&metrics[t]!=null).map(t=>({name:METRICS[t]?.label||t,detail:formatMetric(t,metrics[t])})),note:s.note||null});
export function strengthShareData(s,accent,formatDate){let v=0;const rows=(s.segments||[]).map((seg,i)=>{const d=(seg.entries||[]).map(e=>{const m=e.metrics||{},w=m.weight,r=m.repetitions??'?';if(Number.isFinite(w)&&w>0)v+=w*(Number(r)||0);return`${Number.isFinite(w)?formatNumber(w,1):'?'}×${r}`}).join(' · ');return{name:seg.name||`Übung ${i+1}`,detail:d||'Keine Satzwerte'}});return{accent,eyebrow:'KRAFT · TRAINING',title:s.title||'Krafttraining',date:formatDate(s.date),heroLabel:'TRAININGSVOLUMEN',heroText:`${formatNumber(v,0)} kg`,rows,note:s.note||null}}
