import{id,todayIso,completedSessions,formatDate,formatNumber,parseNumber,esc}from'./core.js';
let editor=null;const clone=x=>structuredClone(x);export const currentStrengthEditor=()=>editor;
export function strengthVolume(s){let v=0;for(const g of s.segments||[]){if(g.status==='draft')continue;for(const e of g.entries||[]){if(e.flags?.includes('warmup'))continue;const m=e.metrics||{},w=Number(m.weight),r=Number(m.repetitions)||0;if(Number.isFinite(w)&&w>0)v+=w*r}}return v}
export function strengthOverview(state){const ss=completedSessions(state,'strength'),cards=ss.slice(0,20).map(s=>`<button class="session" data-action="strength.open" data-id="${s.id}"><span class="session__accent"></span><span class="session__main"><strong>${esc(s.title||'Krafttraining')}</strong><small>${esc(formatDate(s.date))} · ${s.segments?.length||0} Übungen · ${formatNumber(strengthVolume(s),0)} kg</small></span><span class="session__arrow">›</span></button>`).join('');return`<section class="module-hero"><div class="module-hero__icon">🏋️</div><div><span class="eyebrow">Kraft</span><h1>Training</h1><p>${ss.length} abgeschlossene Einheiten</p></div></section><button class="button primary create-button" data-action="strength.new"><span>+</span>Freies Training starten</button><div class="section-title top"><span>Verlauf</span></div><div class="stack">${cards||'<div class="card empty">Noch keine Krafttrainings.</div>'}</div>`}
export function newStrength(){editor={mode:'create',draft:{id:id('session'),moduleId:'strength',date:todayIso(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'draft',title:'Freies Training',note:'',segments:[]}}}
export const editStrength=s=>editor={mode:'edit',draft:clone(s)};export const cancelStrength=()=>editor=null;export const setStrengthTitle=v=>{if(editor)editor.draft.title=v};export const setStrengthNote=v=>{if(editor)editor.draft.note=v};
export function addExercise(state,aid){const a=state.activities.find(x=>x.id===aid);if(!editor||!a)throw Error('Übung nicht gefunden.');editor.draft.segments.push({id:id('segment'),activityId:a.id,name:a.name,title:a.name,status:'completed',entries:[{id:id('entry'),metrics:{},flags:[],source:'manual',status:'completed'}]})}
export const removeExercise=idv=>{if(editor)editor.draft.segments=editor.draft.segments.filter(x=>x.id!==idv)};
export function addSet(gid){const g=editor?.draft.segments.find(x=>x.id===gid);if(!g)return;g.entries.push({id:id('entry'),metrics:{...(g.entries.at(-1)?.metrics||{})},flags:[],source:'prefill',status:'completed'})}
export function removeSet(gid,eid){const g=editor?.draft.segments.find(x=>x.id===gid);if(g)g.entries=g.entries.filter(x=>x.id!==eid)}
export function toggleWarmup(gid,eid){const e=editor?.draft.segments.find(x=>x.id===gid)?.entries.find(x=>x.id===eid);if(!e)return;e.flags??=[];e.flags.includes('warmup')?e.flags=e.flags.filter(x=>x!=='warmup'):e.flags.push('warmup')}
export function setSetMetric(gid,eid,type,raw){const e=editor?.draft.segments.find(x=>x.id===gid)?.entries.find(x=>x.id===eid);if(!e)return;const v=parseNumber(raw);if(v==null)delete e.metrics[type];else e.metrics[type]=v}
export function saveStrength(state){if(!editor)throw Error('Kein Training geöffnet.');if(!editor.draft.segments.length)throw Error('Füge mindestens eine Übung hinzu.');if(!editor.draft.segments.some(g=>g.entries.some(e=>Object.keys(e.metrics).length)))throw Error('Trag mindestens einen Satzwert ein.');const d=clone(editor.draft);d.status='completed';d.updatedAt=new Date().toISOString();if(editor.mode==='create')state.sessions.push(d);else{const i=state.sessions.findIndex(x=>x.id===d.id);if(i<0)throw Error('Training nicht gefunden.');state.sessions[i]=d}editor=null;return d}
export const deleteStrength=(state,idv)=>state.sessions=state.sessions.filter(x=>x.id!==idv);
const row=(g,e,i)=>`<div class="strength-set ${e.flags?.includes('warmup')?'warm':''}"><button class="set-number" data-action="strength.warmup" data-segment="${g.id}" data-set="${e.id}">${e.flags?.includes('warmup')?'A':i+1}</button><label><input value="${e.metrics?.weight??''}" inputmode="decimal" data-change="strength.metric" data-type="weight" data-segment="${g.id}" data-set="${e.id}"><span>kg</span></label><label><input value="${e.metrics?.repetitions??''}" inputmode="numeric" data-change="strength.metric" data-type="repetitions" data-segment="${g.id}" data-set="${e.id}"><span>Wdh</span></label><button class="set-remove" data-action="strength.set.remove" data-segment="${g.id}" data-set="${e.id}">×</button></div>`;
export function strengthEditorView(state){if(!editor)return'<div class="card empty">Kein Training geöffnet.</div>';const acts=state.activities.filter(a=>a.moduleId==='strength'&&!a.archived),opts=acts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join(''),segments=editor.draft.segments.map(g=>`<section class="strength-exercise"><header><div><strong>${esc(g.name)}</strong><small>${g.entries.length} Sätze</small></div><button class="icon small" data-action="strength.exercise.remove" data-segment="${g.id}">×</button></header><div class="strength-sets">${g.entries.map((e,i)=>row(g,e,i)).join('')}</div><button class="button subtle" data-action="strength.set.add" data-segment="${g.id}">+ Satz hinzufügen</button></section>`).join('');return`<section class="module-hero"><div class="module-hero__icon">🏋️</div><div><span class="eyebrow">Kraft</span><h1>${editor.mode==='create'?'Neues Training':'Training bearbeiten'}</h1><p>${formatNumber(strengthVolume(editor.draft),0)} kg aktuell</p></div></section><div class="editor-card stack"><label class="metric-field"><span>Name</span><input data-change="strength.title" value="${esc(editor.draft.title)}"></label><div class="exercise-picker"><select id="strengthExercise">${opts||'<option value="">Keine Übungen importiert</option>'}</select><button class="button" data-action="strength.exercise.add">Übung hinzufügen</button></div></div><div class="stack top">${segments||'<div class="card empty">Füge deine erste Übung hinzu.</div>'}</div><label class="metric-field top"><span>Trainingsnotiz · optional</span><textarea data-change="strength.note">${esc(editor.draft.note||'')}</textarea></label><div class="stack top"><button class="button primary" data-action="strength.save">Training abschließen ✓</button><button class="button" data-action="strength.cancel">Abbrechen</button></div>`}
export function strengthDetailView(state,idv){const s=state.sessions.find(x=>x.id===idv);if(!s)return'<div class="card empty">Training nicht gefunden.</div>';const gs=(s.segments||[]).map(g=>`<section class="strength-detail-exercise"><strong>${esc(g.name||'Übung')}</strong>${(g.entries||[]).map((e,i)=>`<div class="strength-detail-set"><span>${e.flags?.includes('warmup')?'Aufwärmen':`Satz ${i+1}`}</span><strong>${e.metrics?.weight??'–'} kg × ${e.metrics?.repetitions??'–'}</strong></div>`).join('')}</section>`).join('');return`<section class="module-hero"><div class="module-hero__icon">🏋️</div><div><span class="eyebrow">Kraft</span><h1>${esc(s.title||'Krafttraining')}</h1><p>${esc(formatDate(s.date))} · ${formatNumber(strengthVolume(s),0)} kg</p></div></section><div class="detail-card stack">${gs}${s.note?`<p class="tour-note">${esc(s.note)}</p>`:''}</div><div class="action-grid top"><button class="button primary" data-action="strength.share" data-id="${s.id}">Teilen</button><button class="button" data-action="strength.edit" data-id="${s.id}">Bearbeiten</button></div><button class="button danger top" data-action="strength.delete" data-id="${s.id}">Löschen</button>`}
