import{id,todayIso,parseDuration,parseNumber,sessionMetrics,completedSessions,formatMetric,formatDate,esc,METRICS}from'./core.js';
let editor=null;export const currentEditor=()=>editor;const clone=x=>structuredClone(x);
const active=(state,module)=>state?.preferences?.tourMetrics?.[module.id]?.length?state.preferences.tourMetrics[module.id]:[...module.defaultMetrics];
export function newTour(a,b,c){let state,module,date;if(a?.sessions){state=a;module=b;date=c}else{state=null;module=a;date=b}editor={mode:'create',moduleId:module.id,metrics:active(state,module),draft:{id:id('session'),moduleId:module.id,date:date||todayIso(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'draft',title:'',note:'',segments:[{id:id('segment'),activityId:`activity_${module.id}`,entries:[{id:id('entry'),metrics:{},flags:[],source:'manual'}]}]}}}
export function editTour(a,b,c){let state,module,session;if(a?.sessions){state=a;module=b;session=c}else{state=null;module=b;session=a}editor={mode:'edit',moduleId:module?.id||session.moduleId,metrics:active(state,module||{id:session.moduleId,defaultMetrics:Object.keys(sessionMetrics(session))}),draft:clone(session)}}
export const cancelEdit=()=>editor=null;export const setTitle=v=>{if(editor)editor.draft.title=v};export const setNote=v=>{if(editor)editor.draft.note=v};
export function setMetric(module,type,raw){if(!editor)return;const m=sessionMetrics(editor.draft);let v;if(type==='duration')v=parseDuration(raw,module.durationMode);else if(type==='distance'){const n=parseNumber(raw);v=n==null?null:Math.round(n*1000)}else v=parseNumber(raw);if(v==null)delete m[type];else m[type]=v}
export function addOptionalMetric(state,module,type){if(!editor||!module.optionalMetrics.includes(type))return;if(!editor.metrics.includes(type))editor.metrics.push(type);state.preferences.tourMetrics??={};state.preferences.tourMetrics[module.id]=[...editor.metrics]}
export function removeOptionalMetric(state,module,type){if(!editor||!module.optionalMetrics.includes(type))return;editor.metrics=editor.metrics.filter(x=>x!==type);delete sessionMetrics(editor.draft)[type];state.preferences.tourMetrics??={};state.preferences.tourMetrics[module.id]=[...editor.metrics]}
export function saveTour(state){if(!editor)throw Error('Keine Tour geöffnet.');if(!Object.keys(sessionMetrics(editor.draft)).length)throw Error('Trag mindestens einen Wert ein.');const d=clone(editor.draft);d.status='completed';d.updatedAt=new Date().toISOString();if(editor.mode==='create')state.sessions.push(d);else{const i=state.sessions.findIndex(s=>s.id===d.id);if(i<0)throw Error('Tour nicht gefunden.');state.sessions[i]=d}editor=null;return d}
export const deleteTour=(state,id)=>state.sessions=state.sessions.filter(s=>s.id!==id);
const hero=(m,t,s='')=>`<section class="module-hero"><div class="module-hero__icon">${m.icon}</div><div><span class="eyebrow">${esc(m.label)}</span><h1>${esc(t)}</h1>${s?`<p>${esc(s)}</p>`:''}</div></section>`;
export function overview(state,m){const ss=completedSessions(state,m.id),dist=ss.reduce((n,s)=>n+(sessionMetrics(s).distance||0),0),cards=ss.length?ss.map(s=>{const x=sessionMetrics(s),meta=m.listMetrics.filter(t=>x[t]!=null).map(t=>formatMetric(t,x[t])).join(' · ');return`<button class="session" data-action="tour.open" data-id="${s.id}"><span class="session__accent"></span><span class="session__main"><strong>${esc(s.title||m.singular)}</strong><small>${esc(formatDate(s.date))}${meta?' · '+esc(meta):''}</small></span><span class="session__arrow">›</span></button>`}).join(''):`<div class="card empty">Noch keine ${esc(m.plural)}.</div>`;return`${hero(m,m.plural,ss.length?`${ss.length} Einträge · ${formatMetric('distance',dist)}`:'Bereit für deinen ersten Eintrag')}<button class="button primary create-button" data-action="tour.new"><span>+</span>${esc(m.singular)} eintragen</button><div class="section-title top"><span>Zuletzt</span></div><div class="stack">${cards}</div>`}
const val=(t,v)=>v==null?'':t==='duration'?formatMetric(t,v):t==='distance'?String(v/1000).replace('.',','):String(v).replace('.',',');
export function editorView(m){if(!editor)return'<div class="card empty">Kein Entwurf geöffnet.</div>';const d=editor.draft,x=sessionMetrics(d),fields=editor.metrics.map(t=>`<label class="metric-field"><span>${esc(METRICS[t].label)}${METRICS[t].unit?' · '+esc(METRICS[t].unit):''}</span><div class="metric-input-row"><input data-change="tour.metric" data-type="${t}" value="${esc(val(t,x[t]))}" placeholder="${t==='duration'?(m.durationMode==='minutes-seconds'?'35:50':'2:30'):'0'}">${m.optionalMetrics.includes(t)?`<button class="remove-metric" data-action="tour.metric.remove" data-type="${t}">×</button>`:''}</div></label>`).join(''),opts=m.optionalMetrics.filter(t=>!editor.metrics.includes(t)).map(t=>`<button class="chip" data-action="tour.metric.add" data-type="${t}">+ ${esc(METRICS[t].label)}</button>`).join('');return`${hero(m,editor.mode==='create'?`Neue ${m.singular}`:`${m.singular} bearbeiten`,'Werte werden erst beim Speichern übernommen')}<div class="editor-card stack"><label class="metric-field"><span>Name · optional</span><input data-change="tour.title" value="${esc(d.title)}"></label>${fields}<label class="metric-field"><span>Notiz · optional</span><textarea data-change="tour.note">${esc(d.note||'')}</textarea></label></div>${opts?`<p class="section-label">Mehr Werte</p><div class="chip-row">${opts}</div>`:''}<div class="stack top"><button class="button primary" data-action="tour.save">Änderungen speichern</button><button class="button" data-action="tour.cancel">Abbrechen</button></div>`}
export function detail(state,m,id){const s=state.sessions.find(x=>x.id===id);if(!s)return'<div class="card empty">Nicht gefunden.</div>';const x=sessionMetrics(s),rows=m.metrics.filter(t=>x[t]!=null).map(t=>`<div class="detail"><span>${esc(METRICS[t].label)}</span><strong>${esc(formatMetric(t,x[t]))}</strong></div>`).join('');return`${hero(m,s.title||m.singular,formatDate(s.date))}<div class="detail-card stack">${rows}${s.note?`<p class="tour-note">${esc(s.note)}</p>`:''}</div><div class="action-grid top"><button class="button primary" data-action="tour.share" data-id="${s.id}">Teilen</button><button class="button" data-action="tour.edit" data-id="${s.id}">Bearbeiten</button></div><button class="button danger top" data-action="tour.delete" data-id="${s.id}">Löschen</button>`}
